### ISSUE TITLE
VIP Design System Fixes after Tokens Update

### ISSUE THREAD

**Issue by dabowman** [Automattic/vip-design-system#263]
Looks like the border radius and some padding has gone haywire in the dropdown popover.
<img width="428" alt="Screen Shot 2023-10-18 at 12 54 18 PM" src="https://github.com/Automattic/vip-design-system/assets/5473066/325cbe01-6ed8-4d2c-884c-e31f45a1fe4f">

```[tasklist]
### Tasks
- [x] [frontend] Use the proper space value to fix the Radius border for Dropdown items
- [x] [design] Set 0 as 0 for the spaces
- [x] [design] Fix line-height of body to be at least 1.5. It used to be 1.6
- [x] [front] Invert the Headings order in the code. Design system shows from 7 to one, instead of 1 to 7.
```

**Comment by dabowman** [comment]
Looks like there's a hard-coded color value in radio component story. Not sure if that's important, but it should probabyl reference the token color. 
https://github.com/Automattic/vip-design-system/blob/c253c42a0217477e5eeacf93094df0fecfc689d3/src/system/Form/Radio.stories.jsx#L72-L73

**Comment by dabowman** [comment]
Not sure if this is an issue in practice, but the link underlines base their thickness on the em value of the text their applied to, which is fine. But when you hover it changes to 2px, if we ever put a link on a larger type size this could make the underline get smaller on hover which could be weird. Might want to change them both to em values https://github.com/Automattic/vip-design-system/blob/1a148d94a44dc36f866cc1405b5ababbf5a2f2ad/src/system/Link/Link.tsx#L32

**Comment by dabowman** [comment]
There also instances of border radii that we might want to standardize. When we want to fully round an element I've seen it done 3 ways:
https://github.com/Automattic/vip-design-system/blob/1a148d94a44dc36f866cc1405b5ababbf5a2f2ad/src/system/NewDialog/DialogClose.js#L34
https://github.com/Automattic/vip-design-system/blob/1a148d94a44dc36f866cc1405b5ababbf5a2f2ad/src/system/Form/Toggle.js#L57
https://github.com/Automattic/vip-design-system/blob/1a148d94a44dc36f866cc1405b5ababbf5a2f2ad/src/system/Avatar/Avatar.tsx#L30
it would be pretty easy to include a token to fully round an element something like `borderRadius.full`

**Comment by dabowman** [comment]
Here's a hard-coded font weight that could be replaced 
https://github.com/Automattic/vip-design-system/blob/1a148d94a44dc36f866cc1405b5ababbf5a2f2ad/src/system/NewDialog/DialogTitle.js#L22

**Comment by dabowman** [comment]
I'm pretty sure the overlay color token includes the opacity. We might not need to declare opacity here as well 
https://github.com/Automattic/vip-design-system/blob/1a148d94a44dc36f866cc1405b5ababbf5a2f2ad/src/system/NewDialog/DialogOverlay.js#L21

**Comment by dabowman** [comment]
hard-coded line-height https://github.com/Automattic/vip-design-system/blob/4e1b921fe54f9007c203c8fcbafb9427e9b8b233/src/system/NewForm/FormAutocomplete.js#L37

**Comment by dabowman** [comment]
more hard-coded values 
https://github.com/Automattic/vip-design-system/blob/4e1b921fe54f9007c203c8fcbafb9427e9b8b233/src/system/NewForm/FormAutocomplete.js#L49
https://github.com/Automattic/vip-design-system/blob/4e1b921fe54f9007c203c8fcbafb9427e9b8b233/src/system/NewForm/FormAutocomplete.js#L54
https://github.com/Automattic/vip-design-system/blob/4e1b921fe54f9007c203c8fcbafb9427e9b8b233/src/system/NewForm/FormAutocomplete.js#L82

These are referenced to really old styles 
https://github.com/Automattic/vip-design-system/blob/4e1b921fe54f9007c203c8fcbafb9427e9b8b233/src/system/NewForm/FormAutocomplete.js#L72
https://github.com/Automattic/vip-design-system/blob/4e1b921fe54f9007c203c8fcbafb9427e9b8b233/src/system/NewForm/FormAutocomplete.js#L73

**Comment by dabowman** [comment]
More hard-coded values that should probably get replaced 
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocomplete.js#L348

**Comment by dabowman** [comment]
few more hard-coded values 
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocomplete.stories.jsx#L154

**Comment by dabowman** [comment]
Nothing too crazy is going on here but i feel like there must be an easier way to do this ... https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocompleteMultiselect.js#L105

**Comment by dabowman** [comment]
values that can be replaced with tokens: 
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocompleteMultiselect.js#L37
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocompleteMultiselect.js#L49
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocompleteMultiselect.js#L54
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocompleteMultiselect.js#L86
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocompleteMultiselect.js#L410
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormSelect.js#L28

I've seen this implementation in form inputs, not sure if it's necessary but it probably isn't very responsive. If the line height needs to match the min-height we should probably at least use rem values instead of px. 

is this the correct token name? or is this old. 
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocompleteMultiselect.js#L73
Some other old style references: 
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocompleteMultiselect.js#L76
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormAutocompleteMultiselect.js#L77

**Comment by dabowman** [comment]
can replace with token 
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormSelectLoading.js#L28

**Comment by dabowman** [comment]
replace with tokens 
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/NewForm/FormSelectSearch.js#L16

**Comment by dabowman** [comment]
replace with tokens 
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/OptionRow/OptionRow.js#L80

**Comment by dabowman** [comment]
old color token reference to replace 
https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/Wizard/Wizard.js#L59

**Comment by dabowman** [comment]
replace with token https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/Wizard/WizardStep.js#L93

**Comment by dabowman** [comment]
replace with token https://github.com/Automattic/vip-design-system/blob/0237d38436ee13d439d308346b50add6789d75a0/src/system/Wizard/WizardStep.js#L142

**Comment by dabowman** [comment]
> Looks like there's a hard-coded color value in radio component story. Not sure if that's important, but it should probabyl reference the token color.
> 
> https://github.com/Automattic/vip-design-system/blob/c253c42a0217477e5eeacf93094df0fecfc689d3/src/system/Form/Radio.stories.jsx#L72-L73

this color can get replaced with `text.error`

**Comment by dabowman** [comment]
> Not sure if this is an issue in practice, but the link underlines base their thickness on the em value of the text their applied to, which is fine. But when you hover it changes to 2px, if we ever put a link on a larger type size this could make the underline get smaller on hover which could be weird. Might want to change them both to em values
> 
> https://github.com/Automattic/vip-design-system/blob/1a148d94a44dc36f866cc1405b5ababbf5a2f2ad/src/system/Link/Link.tsx#L32

I don't see this working as expected. Links are getting 1px underlines instead of .1em. I do generally prefer em values to px so that it looks correct as font sizes scale. I would suggest .1em for default and .15em for hover. it looks the same at small sizes but scales much better. I'm not sure why the default style isn't working though. We'd need to investigate.

**Comment by dabowman** [comment]
> Here's a hard-coded font weight that could be replaced
> 
> https://github.com/Automattic/vip-design-system/blob/1a148d94a44dc36f866cc1405b5ababbf5a2f2ad/src/system/NewDialog/DialogTitle.js#L22

[Fixed this ](https://github.com/Automattic/vip-design-system/commit/dcf0e5bbf00cc0712a8fb5d2176dd08edd257a5f)

**Comment by djalmaaraujo** [comment]
> textDecorationThickness

https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness. This is not a well-supported feature across browsers, especially if you use % values.
